#!/bin/sh

if [ $# -lt 1 ]
then
    echo "supply build number as the first argument"
    exit 1
fi

VERSION="0.1-$1"
PACKAGE=oh-pipeline-service
TOPDIR=debian

# mvn build
mvn -DVERSION=$VERSION clean install cobertura:cobertura

# create deb tree
APP_LOG_DIR=./$TOPDIR/var/log/$PACKAGE
TOMACT_WORK_DIR=./$TOPDIR/var/cache/$PACKAGE
APP_CONF_DIR=./$TOPDIR/etc/default
TOMCAT_CONF_DIR=./$TOPDIR/etc/$PACKAGE
CATALINA_BASE=./$TOPDIR/var/lib/$PACKAGE
TOMCAT_WEB_DIR=$CATALINA_BASE/webapps

mkdir -p $APP_LOG_DIR
mkdir -p $TOMACT_WORK_DIR
mkdir -p $APP_CONF_DIR
mkdir -p $TOMCAT_WEB_DIR
mkdir $TOMCAT_CONF_DIR
mkdir $CATALINA_BASE/common
mkdir $CATALINA_BASE/server
mkdir $CATALINA_BASE/shared

# set dir mode
find ./$TOPDIR -type d | xargs chmod 755

cp ./src/main/tomcat/conf/server.xml $TOMCAT_CONF_DIR
cp -r ./target/${PACKAGE}-${VERSION}/* $TOMCAT_WEB_DIR
cp ./src/main/conf/${PACKAGE} $APP_CONF_DIR

# create deb package
oh-deb-build $VERSION

# clean up build root (topdir)
rm -rf ./$TOPDIR
