#!/bin/sh

# change permissions
chown tomcat6:adm /var/log/${PACKAGE}
chown tomcat6:adm /var/cache/${PACKAGE}
chown -R tomcat6:tomcat6 /var/lib/${PACKAGE}/common
chown -R tomcat6:tomcat6 /var/lib/${PACKAGE}/server
chown -R tomcat6:tomcat6 /var/lib/${PACKAGE}/shared

chown root:tomcat6 /etc/${PACKAGE}/*

# config - share with tomcat installation
ln -s /etc/tomcat6/catalina.properties /etc/${PACKAGE}/catalina.properties
ln -s /etc/tomcat6/context.xml /etc/${PACKAGE}/context.xml
ln -s /etc/tomcat6/logging.properties /etc/${PACKAGE}/logging.properties
ln -s /etc/tomcat6/policy.d /etc/${PACKAGE}/policy.d
ln -s /etc/tomcat6/tomcat-users.xml /etc/${PACKAGE}/tomcat-users.xml
ln -s /etc/tomcat6/web.xml /etc/${PACKAGE}/web.xml

ln -s /etc/${PACKAGE} /var/lib/${PACKAGE}/conf
ln -s /var/log/${PACKAGE} /var/lib/${PACKAGE}/logs
ln -s /var/cache/${PACKAGE} /var/lib/${PACKAGE}/work

# create startup script
ln -s /etc/init.d/tomcat6 /etc/init.d/${PACKAGE}
