#!/bin/sh

ln -s /etc/init.d/oh-pipeline-service /etc/init.d/${PACKAGE}
ln -s /var/lib/tomcat7/conf/web.xml /var/app/${PACKAGE}/web.xml

chown tomcat7:tomcat7 /var/app/${PACKAGE}/webapps
chown tomcat7:tomcat7 /var/app/${PACKAGE}/work
chown tomcat7:tomcat7 /var/app/${PACKAGE}/conf
